### ISSUE TITLE
Wallet Not Syncing

### ISSUE THREAD

**Issue by alingb** [STATION-I/stai-blockchain#32]
After the old version address is imported, the wallet synchronization is always 0？

**Comment by WarutaShinken** [comment]
Sorry for the late response, but this is probably because the DNS introducer, which the wallet relies on for automatically getting connections, has a seemingly non-functional domain name (`dns-introducer.staicoin.com`). However, it does work through `introducer.staicoin.com`. Could you go into `config.yaml` and replace the domain name under `wallet:` (consider doing this for `full_node:` as well)?

**Comment by WarutaShinken** [comment]
I will close this since there's no one else posting here and the standalone wallet is able to connect on it's own on a fresh install.
